### ISSUE TITLE
MonaServer project doesn't compile (just MonaTiny build)

### ISSUE THREAD

**Issue by nobme** [MonaSolutions/MonaServer2#1]
Some error in the project.
 File MapParameters.h seems to be missing.
 MonaBase compile OK in Windows, but makefile not working.
 MonaCore compile OK in Windows, but makefile not working.
 MonaTiny compile OK in Windows, but makefile not working.
 UnitTest compile OK in Windows, but makefile not working.
 MonaServer do not compile, due to missing MapParameters.h

**Comment by thomasjammet** [comment]
Hi,

I have just updated the [Readme file](https://github.com/MonaSolutions/MonaServer2/blob/master/README.md) so you can see our progress.

All the best
Thomas

**Comment by MathieuPOUX** [comment]
Hi,

Yes as saying Thomas MonaServer2 is in developpment status and should replace MonaServer in the next months. There is almost 2 years of job behind, mainly on foundation (events, threads, socket/file async, performance), it should start a new age for Mona, with new features, new protocols, to concurrent in open source any other web server (media server but also web server).
Now we work often freely behind mona, and we are forced to break everytime mona job to catch "eating" mission :-) I mean by this way, in using this post issue,  that we are always searching financial resource/investissor to work more time on Mona.
Mona potential is enormous, a word to the wise ;-)

Best regards,
Mathieu
