### ISSUE TITLE
compile monaserver2 display error

### ISSUE THREAD

**Issue by jobsguo** [MonaSolutions/MonaServer2#12]
Hi, when i compile MonaCore,  it display below err:

Error 	C2664	“std::pair<const _Kty,_Ty>::pair(std::pair<const _Kty,_Ty> &&)”: 无法将参数 2 从“Mona::HTTP::RendezVous::Remote *”转换为“const std::unique_ptr<const Mona::HTTP::RendezVous::Remote,std::default_delete<_Ty>> &”	MonaCore	E:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xmemory0	655	

Could you help me ?ths.

**Comment by thomasjammet** [comment]
Hi,

This is strange, I do not have this error. Could you try to pull the last version from github, clean up the project and build it again?
If it happens again please give us more details on how you build MonaServer2.

Thanks
