### ISSUE TITLE
MonaServer2 Compile error

### ISSUE THREAD

**Issue by davidka79** [MonaSolutions/MonaServer2#13]
Hello
I am trying to compile monaserver2 
I made a git clone master and just run a make as in read.me file but getting the error :(

g++5 is present, openssl-dev is present

thank you 

[monaserver2.compile.log](https://github.com/MonaSolutions/MonaServer2/files/1950039/monaserver2.compile.log)

**Comment by MathieuPOUX** [comment]
Hi David,
Sorry MonaServer2 has always no LUA port, you can build just MonaTiny (a pure CPP server without LUA part).

I close this issue because is duplicated with https://github.com/MonaSolutions/MonaServer2/issues/1

**Comment by davidka79** [comment]
Hello and thank you for response, 
but I cant compile MonaTiny also
it requires MonaBase and MonaCore 
MonaCore is not compiling
MonaBase is ok :(
[monaserver2.compile.log](https://github.com/MonaSolutions/MonaServer2/files/1951148/monaserver2.compile.log)

**Comment by thomasjammet** [comment]
Yes the compile log file is quite clear, though it should compile, could you try updating gcc to a more recent version?
Otherwise tell us which distribution you are using and the result of "g++ -v"

Thanks

**Comment by davidka79** [comment]
Ubuntu Server 16.04
the version of g++

Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.9' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)


Thank you

**Comment by thomasjammet** [comment]
Hi,

I have made a correction, it should compile now!

**Comment by davidka79** [comment]
Thank you very much!!!

MonaCore ok
MonaBase ok
MonaTiny ok

and thanks for a great server 
we was needed RTMP Live and tested 
nginx_rtmp_module - very good but a bit slow with more than 100 publishers
srs rtmp v1 v2 v3 - fast but unstable and have problems with elementary encoder and adobe radio streamer
MonaServer v1 for now covers all our needs
MonaServer v2 (Tiny) will be tested but if I will not find how to make an authentication http hook up onPublish and onPlay then it will be useless for us :(
