### ISSUE TITLE
Multiple issues during use - please open for details

### ISSUE THREAD

**Issue by pnguyencong** [MonaSolutions/MonaServer2#14]
System : 
Ryzen 1700x
16gb RAM
1080ti
Windows 10
Hardwire LAN / 250mbps down / 20 up
Used standard issue x64 build ( I did not build my own from git )

Use : 

8 OBS rtmp feeds incoming from 8 different pcs around the nation pointed towards my MonaServer2 - which I then pull those in as VLC inputs to my own instance of OBS and do POV mixing/production

History : This has worked flawlessly in the past ( 9 months ago ) - with zero errors in the console

Problem : Used it this weekend for an event - had multiple instances of the following errors

congested session
insufficient video bandwidth

which obviously caused signal drop into OBS - but also caused my stream to another MonaServer to go to 0kbps.  for 10-15 seconds while it settled back in and then it was back to business - this would happen once every 15-20 minutes which was really a downer.

I tested this again on a windows server 2008 box and another win10 as well.  Same issues.

Any help is appreciated.  I never took the time to build my own, due to the standard issue not having any issues 9 months ago.  ( good enough for my needs at the time ) 

* I can provide a log later if needed.

**Comment by thomasjammet** [comment]
Hi,

We are used to have congestion with OBS which is buffering over and over during use. Our congestion detection system is quite aggressive and you can try to increase the socket buffer using the net.bufferSize configuration parameter :
Create and open the MonaTiny.ini file on the same level as MonaTiny executable. Then write these 2 lines :
```
[net]
bufferSize=2129920
```
You can then restart MonaTiny with the argument "--log=7" and you should see these 2 lines :
```
server.cpp[32] Socket receiving buffer size of 212992 bytes
server.cpp[33] Socket sending buffer size of 212992 bytes
```

Though I suggest you to try avoiding buffering, take a look at [this post on OBS forum](https://obsproject.com/forum/threads/my-stream-lags-buffers-loads-constantly-for-my-viewers-but-why.18465/) which could help you with this kind of OBS problems.

**Comment by thomasjammet** [comment]
Hello,

It depends on your need, you can use ffmpeg if you just need to [share a screen](https://trac.ffmpeg.org/wiki/Capture/Desktop) or [a camera](https://trac.ffmpeg.org/wiki/Capture/Webcam) but there is no real alternative to OBS.

**Comment by thomasjammet** [comment]
Eventually there is [Xsplit](https://www.xsplit.com/) if you are always searching an alternative.
