### ISSUE TITLE
Any plans for a Docker image for MonaTiny?

### ISSUE THREAD

**Issue by reedog117** [MonaSolutions/MonaServer2#16]
Any plans for a Docker image for MonaTiny to be accessible from the Docker Hub?

**Comment by thomasjammet** [comment]
I have spent some time to add monaserver 1 to the Docker Hub but they didn't accept the request, I have finally decided to forget it as is it is not our priority.
Though you can find a Dockerfile for MonaTiny at https://github.com/potsky/mona/blob/master/Dockerfile
If you want to try to add MonaTiny to the Docker Hub you are welcome and your efforts would be really appreciated!

**Comment by thomasjammet** [comment]
Forget about the Docker Hub previous comment, I was confusing with the Docker [Official Repository](https://hub.docker.com/explore/). 
When I have time I will try to add ad docker image of MonaTiny, for now there is already MonaServer 1 accessible from thomasjammet/docker-mona (https://github.com/MonaSolutions/docker-mona)

**Comment by thomasjammet** [comment]
MonaTiny has been added to docker !

```
docker pull thomasjammet/docker-mona:alpine-monatiny
```

```
docker run -it --name MonaTiny -p 80:80 -p 1935:1935 -p 443:443 -p 1935:1935/udp thomasjammet/docker-mona:alpine-monatiny
```

This is just an example of the most simple MonaTiny docker image. If you need another distribution feel free to send a pull request with your Dockerfile.
