### ISSUE TITLE
HTTP live streaming

### ISSUE THREAD

**Issue by maffbm** [MonaSolutions/MonaServer2#18]
Hi, current  MonaServer user, looking into moving to MonaServer2 and I'm especially interested in http streaming. I've seen this post: https://github.com/MonaSolutions/MonaServer/issues/71

Can anyone expand on that?
I'm using OBS for the video stream.
Where would the html page sit? in the www folder?
I have port 80, 8080 and some others in use on my PC, so looking to use 8084

Any help appreciated with this, thank you v much

**Comment by thomasjammet** [comment]
Yes exactly, you put directly the page in www.

To set the port 8084 for HTTP you have to create a MonaTiny.ini file at the same level as MonaTiny.exe with this content :
```
[HTTP]
port=8084
```

Then restart MonaTiny and you can go to http://localhost/yourpage.html to test your page.
Notice that you can also play your stream without a web page with http://localhost/yourstream.mp4

**Comment by maffbm** [comment]
Brilliant, thank you!

**Comment by maffbm** [comment]
hmm, OK, the page loads fine, however, I cannot get the video to play, I've tried:
localhost/test.mp4
localhost/live/test.mp4
localhost:8084/test.mp4
localhost:8084/live/test.mp4

OBS is set with URL of: rtmp://127.0.0.1 & stream key is "test", Mona see it as a connection when I start streaming

**Comment by maffbm** [comment]
Still getting the same Mathieu, OBS 22.0.1

**Comment by MathieuPOUX** [comment]
Can you please come in on hangout? (mathieu.poux[a]gmail.com)

**Comment by maffbm** [comment]
invitation sent

**Comment by MathieuPOUX** [comment]
Was a problem with binaries version not updated, we have just updated if and maffbm confirms it works.
