### ISSUE TITLE
Would it be possible to have MonaTiny compile for linux?

### ISSUE THREAD

**Issue by nobme** [MonaSolutions/MonaServer2#2]
MonaTiny compile in Windows, but does not compile in Linux. Could it be possible in the near feature?

**Comment by MathieuPOUX** [comment]
MonaTiny compile on Linux on my side (tested on 32 and 64 bits), beware it requires at less g++ 5.
Otherwise shares errors here to try to fix it.

**Comment by nobme** [comment]
OK. Updated to g++ 6.3.
Now MonaTiny compiles, but is not stable (rtmp streaming from obs-studio as source, Vlc to play.).
Stream is stopping with both Audio and Video timeout.
Subsription.cpp[250] Audio timeout, insufficient bandthwith to play
Subsription.cpp[300] Video timeout, insufficient bandthwith to play
These messages are warnings in the log.
Any idea?

**Comment by thomasjammet** [comment]
Hi

It is exactly what it seems to be. This message is sent when there is not enough bandwidth on your network to download the video from the server. Can you try to lower the quality of your video? 

If it doesn't resolve your problem tell us what is your environment (network, OS, protocol used, client application...).

**Comment by nobme** [comment]
I have two equal setup. 
One with the 'old' MonaServer, and the other with MonaTiny.
AllHW are the same.
For the detail around the setup, see https://github.com/MonaSolutions/MonaServer/issues/48
MonaServer is streaming stable (as long you have available memory...), MonaTiny stop, as described.
I'm Streaming with OBS (2500KB) 720p50, in both test. 

So, the big question is.. 
Is this a weakness of MonaTiny, and will MonaServer #2 be better?

**Comment by thomasjammet** [comment]
Hi,

This is mostly an improvement of MonaTiny, we close the subscriptions when a player is creating congestion, this is saving from a memory/crash issue in Mona!
What you can do is lower the quality (2,5Mb is a lot) of your publication or publish with many different framerates. Then in your player application you could try to connect to streams with lower quality when you receive the "insufficient bandwidth" message or calculate the client bandwidth and choose the right stream before any subscription.

What do you think of this?
