### ISSUE TITLE
Restrict stream content source from local network only

### ISSUE THREAD

**Issue by swaggerwocky** [MonaSolutions/MonaServer2#21]
Hello, is there any way to restrict stream sources to only those from the local network? For example, I want MonaTiny to accept stream publication from 192.168.1.* only.

**Comment by MathieuPOUX** [comment]
Hi,

You could set an exception on connection in MonaTiny::onConnection
<https://github.com/MonaSolutions/MonaServer2/blob/master/MonaTiny/sources/MonaTiny.cpp#L100>
to
reject a client when client.address.host().isSiteLocal() returns false, but
I recommend rather to use a system tool like iptables
<https://www.linode.com/docs/security/firewalls/control-network-traffic-with-iptables/>
(or
other firewall rules) for performance reason to not encumber server and its
main thread with this possibly recurrent/numerous tasks. System tools are
more appropriate in this case (closer to the ethernet material).

Le dim. 17 mars 2019 à 05:29, swaggerwocky <notifications@github.com> a
écrit :

**Comment by swaggerwocky** [comment]
thanks!
