### ISSUE TITLE
MonaTiny + Lua maybe need some love with this library

### ISSUE THREAD

**Issue by gdeverlant** [MonaSolutions/MonaServer2#22]
Hi I've found this library which seem to be really well built. Since MonaServer1 had lua is it going to be implemented the same way or are you looking for new ways?

I hope this can help to simplify the lua integration: https://github.com/Leandros/sol2

**Comment by thomasjammet** [comment]
Hi,

We are working on it, it will be similar to the last implementation yes.

Thanks for the link, I don't think this will help as we will integrate luajit on the lowest possible level.
