### ISSUE TITLE
POCO C++ Libraries Attribution

### ISSUE THREAD

**Issue by obiltschnig** [MonaSolutions/MonaServer2#24]
Hi folks, I saw that you took some "inspiration" (and also some code I wrote) from the POCO C++ Libraries. I'm referring to classes like HelpFormatter, WinRegistry, WinService, Application and ServerApplication in MonaBase. As one of the main authors and copyright holders, I'm generally fine with that, but please play fair and add a proper attribution to that, e.g., "This code is in part based on code from the POCO C++ Libraries, licensed under the Boost software license." Simply taking and modifying code and then putting it under a different license without proper attribution is not the way to go.
Thanks for playing fair.

**Comment by obiltschnig** [comment]
Hi Thomas, thanks for the prompt response. No hard feelings - glad you like POCO.

**Comment by MathieuPOUX** [comment]
Yes, completely right, MonaBase includes few full pieces of code gotten especially from Poco::Util ( HelpFormatter, WinRegistry, WinService, Application, ServerApplication, Option) and we have to quote its source and its authors!
What could be the best convenient form relating you Günter to fix it?
Maybe the both following addition:
- A header sentence in these files as "freely derived from Poco framework code (pocoproject.org)" or "freely inspired...", better proposition?
- A comment with thanks in the Readme of MonaBase project

**Comment by thomasjammet** [comment]
> 
> 
> Yes, completely right, MonaBase includes few full pieces of code gotten especially from Poco::Util ( HelpFormatter, WinRegistry, WinService, Application, ServerApplication, Option) and we have to quote its source and its authors.
> What could be the best convenient way to fix it relating you Günter?
> Maybe the both following addition:
> 
>     * A header sentence in these files as "freely derived from Poco framework code (pocoproject.org)" or "freely inspired...", better proposition?
> 
>     * A comment with thanks in the Readme of MonaBase project

@obiltschnig Any thoughts on this?

**Comment by obiltschnig** [comment]
An attribution at the beginning of the source file is sufficient, along with the Boost License text or a link to it.

**Comment by thomasjammet** [comment]
I have just commited here : 0fb3c4c2277fda5845d1eea98ec99aed5bb984a1

Let me know if you feel ok with this attribution.

**Comment by obiltschnig** [comment]
Looks good. OK for me.
