### ISSUE TITLE
MonaServer (1/2) Does not compile on CentOS 7

### ISSUE THREAD

**Issue by jam65st** [MonaSolutions/MonaServer2#34]
Hi, I want to test *MonaServer* in CentOS 7, but during make, I get these messages:

> [ctoman@centos ~]$ cd MonaServer2/
> [ctoman@centos MonaServer2]$ whereis gcc
gcc: /usr/bin/gcc /usr/lib/gcc /usr/libexec/gcc /usr/share/man/man1/gcc.1.gz
[ctoman@centos MonaServer2]$ make
cd MonaBase && make && cd ../MonaCore && make && cd ../MonaTiny && make && cd ../MonaServer && make && cd ../UnitTests && make
make[1]: Entering directory `/home/ctoman/MonaServer2/MonaBase'
mkdir -p tmp/release
mkdir -p lib
make[2]: Entering directory `/home/ctoman/MonaServer2/MonaBase'
compiling sources/IPAddress.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/IPAddress.o] Error 1
compiling sources/BufferPool.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/BufferPool.o] Error 1
compiling sources/UDPSocket.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/UDPSocket.o] Error 1
compiling sources/TCPClient.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/TCPClient.o] Error 1
compiling sources/IOFile.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/IOFile.o] Error 1
compiling sources/Options.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/Options.o] Error 1
compiling sources/Timezone.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/Timezone.o] Error 1
compiling sources/PersistentData.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/PersistentData.o] Error 1
compiling sources/DiffieHellman.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/DiffieHellman.o] Error 1
compiling sources/Congestion.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/Congestion.o] Error 1
compiling sources/Timer.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/Timer.o] Error 1
compiling sources/ThreadPool.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/ThreadPool.o] Error 1
compiling sources/Path.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/Path.o] Error 1
compiling sources/String.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/String.o] Error 1
compiling sources/IOSRTSocket.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/IOSRTSocket.o] Error 1
compiling sources/TCPServer.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/TCPServer.o] Error 1
compiling sources/Socket.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/Socket.o] Error 1
compiling sources/Process.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/Process.o] Error 1
compiling sources/URL.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/URL.o] Error 1
compiling sources/FileSystem.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/FileSystem.o] Error 1
compiling sources/UnitTest.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/UnitTest.o] Error 1
compiling sources/Packet.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/Packet.o] Error 1
compiling sources/Parameters.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/Parameters.o] Error 1
compiling sources/Date.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/Date.o] Error 1
compiling sources/FileWatcher.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/FileWatcher.o] Error 1
compiling sources/TerminateSignal.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/TerminateSignal.o] Error 1
compiling sources/Net.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/Net.o] Error 1
compiling sources/BitReader.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/BitReader.o] Error 1
compiling sources/IOSocket.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/IOSocket.o] Error 1
compiling sources/Crypto.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/Crypto.o] Error 1
compiling sources/Handler.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/Handler.o] Error 1
compiling sources/ThreadQueue.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/ThreadQueue.o] Error 1
compiling sources/File.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/File.o] Error 1
compiling sources/Thread.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/Thread.o] Error 1
compiling sources/Option.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/Option.o] Error 1
compiling sources/FileLogger.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/FileLogger.o] Error 1
compiling sources/TLS.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/TLS.o] Error 1
compiling sources/BinaryReader.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/BinaryReader.o] Error 1
compiling sources/DNS.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/DNS.o] Error 1
compiling sources/SRT.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/SRT.o] Error 1
compiling sources/SocketAddress.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/SocketAddress.o] Error 1
compiling sources/HelpFormatter.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/HelpFormatter.o] Error 1
compiling sources/ConsoleLogger.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/ConsoleLogger.o] Error 1
compiling sources/Logs.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/Logs.o] Error 1
compiling sources/XMLParser.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/XMLParser.o] Error 1
compiling sources/Signal.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/Signal.o] Error 1
compiling sources/BinaryWriter.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/BinaryWriter.o] Error 1
compiling sources/Mona.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/Mona.o] Error 1
compiling sources/ServerApplication.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/ServerApplication.o] Error 1
compiling sources/HostEntry.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/HostEntry.o] Error 1
compiling sources/Buffer.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/Buffer.o] Error 1
compiling sources/Proxy.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/Proxy.o] Error 1
compiling sources/Util.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/Util.o] Error 1
compiling sources/Application.cpp
g++: error: unrecognized command line option '-std=c++14'
make[2]: *** [tmp/release/Application.o] Error 1
make[2]: Leaving directory `/home/ctoman/MonaServer2/MonaBase'
make[1]: *** [release] Error 2
make[1]: Leaving directory `/home/ctoman/MonaServer2/MonaBase'
make: *** [release] Error 2

**Comment by thomasjammet** [comment]
Hi

To compile MonaServer2 you need at least gcc 5. On CentOS you have to use devtoolset for now, here is a link with installation instructions : https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/
Then you can enable devtoolset by default in your `~/.bashrc` file to never think about it.

**Comment by jam65st** [comment]
Thanks a lot @thomasjammet 

Following your instructions, I can *make* the build, but now I have other derivate Issue:

> [ctoman@centos MonaServer2]$ ./MonaServer/MonaServer
./MonaServer/MonaServer: error while loading shared libraries: libMonaBase.so: cannot open shared object file: No such file or directory

but:

> [ctoman@centos MonaServer2]$ ls -l MonaBase/lib
total 18500
-rw-rw-r--. 1 ctoman ctoman 14554982 May 25 07:00 libMonaBase.a
-rwxrwxr-x. 1 ctoman ctoman  4386176 May 25 07:00 libMonaBase.so

[_extra info_]:
**gcc** version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)
**LuaJIT** 2.0.5

**Comment by Felk** [comment]
I am experiencing the same issue on Debian 10:
```
$ cat /proc/version
Linux version 4.19.0-9-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07)
$ sudo apt info luajit
Package: luajit
Version: 2.1.0~beta3+dfsg-5.1
...
```

```
$ make -j 4 ENABLE_SRT=1
cd MonaBase && make && cd ../MonaCore && make && cd ../MonaTiny && make && cd ../MonaServer && make && cd ../UnitTests && make
make[1]: Entering directory '/home/felk/monaserver2_install_stuff/MonaServer2/MonaBase'
mkdir -p tmp/release
mkdir -p lib
make[2]: Entering directory '/home/felk/monaserver2_install_stuff/MonaServer2/MonaBase'
make[2]: 'tmp/release/IPAddress.o' is up to date.
...
make[2]: 'tmp/release/Application.o' is up to date.
make[2]: Leaving directory '/home/felk/monaserver2_install_stuff/MonaServer2/MonaBase'
creating dynamic lib lib/libMonaBase.so
creating static lib lib/libMonaBase.a
make[1]: Leaving directory '/home/felk/monaserver2_install_stuff/MonaServer2/MonaBase'
make[1]: Entering directory '/home/felk/monaserver2_install_stuff/MonaServer2/MonaCore'
mkdir -p tmp/release
mkdir -p lib
make[2]: Entering directory '/home/felk/monaserver2_install_stuff/MonaServer2/MonaCore'
make[2]: 'tmp/release/MP3Reader.o' is up to date.
...
make[2]: 'tmp/release/RTMFProtocol.o' is up to date.
make[2]: Leaving directory '/home/felk/monaserver2_install_stuff/MonaServer2/MonaCore'
creating dynamic lib lib/libMonaCore.so
make[1]: Leaving directory '/home/felk/monaserver2_install_stuff/MonaServer2/MonaCore'
make[1]: Entering directory '/home/felk/monaserver2_install_stuff/MonaServer2/MonaTiny'
mkdir -p tmp/release/
make[2]: Entering directory '/home/felk/monaserver2_install_stuff/MonaServer2/MonaTiny'
make[2]: 'tmp/release/MonaTiny.o' is up to date.
make[2]: 'tmp/release/main.o' is up to date.
make[2]: Leaving directory '/home/felk/monaserver2_install_stuff/MonaServer2/MonaTiny'
creating executable MonaTiny
make[1]: Leaving directory '/home/felk/monaserver2_install_stuff/MonaServer2/MonaTiny'
make[1]: Entering directory '/home/felk/monaserver2_install_stuff/MonaServer2/MonaServer'
mkdir -p tmp/release/
make[2]: Entering directory '/home/felk/monaserver2_install_stuff/MonaServer2/MonaServer'
make[2]: 'tmp/release/LUAPacket.o' is up to date.
...
make[2]: 'tmp/release/LUAPublications.o' is up to date.
make[2]: Leaving directory '/home/felk/monaserver2_install_stuff/MonaServer2/MonaServer'
creating executable MonaServer
make[1]: Leaving directory '/home/felk/monaserver2_install_stuff/MonaServer2/MonaServer'
make[1]: Entering directory '/home/felk/monaserver2_install_stuff/MonaServer2/UnitTests'
mkdir -p tmp/release/
make[2]: Entering directory '/home/felk/monaserver2_install_stuff/MonaServer2/UnitTests'
make[2]: 'tmp/release/BufferTest.o' is up to date.
...
make[2]: 'tmp/release/IPAddressTest.o' is up to date.
make[2]: Leaving directory '/home/felk/monaserver2_install_stuff/MonaServer2/UnitTests'
creating executable UnitTests
make[1]: Leaving directory '/home/felk/monaserver2_install_stuff/MonaServer2/UnitTests'
```

```
$ ./MonaServer/MonaServer
./MonaServer/MonaServer: error while loading shared libraries: libMonaBase.so: cannot open shared object file: No such file or directory
$ ls -l MonaBase/lib/
total 19372
-rw-r--r-- 1 felk felk 15262552 Feb 25 16:44 libMonaBase.a
-rwxr-xr-x 1 felk felk  4568600 Feb 25 16:44 libMonaBase.so
```

**Comment by thomasjammet** [comment]
Hi Felix,

Sorry I have seen that the README file was incorrect. I have just made an update. So the correct answer is :
```
cd MonaServer
./MonaServer
```

I will let this ticket open to not forget to add a "make install" step to our Makefile so MonaServer will be available from any directory and the libraries MonaBase and MonaCore installed on the system.

**Comment by MathieuPOUX** [comment]
I have fixed some issues in makefile which linked library in a relative way, now is absolute (see [#34](https://github.com/MonaSolutions/MonaServer2/commit/adf03136a8e552c5c565ea1fcabb089b3f05af14)). Would fix any execution wharever the current folder.

**Comment by Felk** [comment]
thank you, that worked, at least for me
