### ISSUE TITLE
Problem make on macos .15

### ISSUE THREAD

**Issue by akarupt** [MonaSolutions/MonaServer2#35]
In file included from sources/Subscription.cpp:19:
In file included from ./include/Mona/Subscription.h:22:
In file included from ./../MonaBase/include/Mona/Congestion.h:21:
In file included from ./../MonaBase/include/Mona/Net.h:20:
In file included from ./../MonaBase/include/Mona/Exceptions.h:20:
./../MonaBase/include/Mona/String.h:255:10: error: call to 'Append' is ambiguous
                return Append<OutType>((OutType&)out.append(value, size ...
                       ^~~~~~~~~~~~~~~
./../MonaBase/include/Mona/String.h:368:10: note: in instantiation of function
      template specialization 'Mona::String::Append<Mona::String, const char, 3,
      Mona::Media::Video::Frame &, char const (&)[2]>' requested here
                return Append<OutType>((OutType&)out.append(buffer,strle...
                       ^
./../MonaBase/include/Mona/String.h:255:10: note: in instantiation of function
      template specialization 'Mona::String::Append<Mona::String, char const
      (&)[3], Mona::Media::Video::Frame &, char const (&)[2]>' requested here
                return Append<OutType>((OutType&)out.append(value, size ...
                       ^
./../MonaBase/include/Mona/String.h:368:10: note: in instantiation of function
      template specialization 'Mona::String::Append<Mona::String, const char, 3,
      unsigned int &, char const (&)[3], Mona::Media::Video::Frame &, char const
      (&)[2]>' requested here
                return Append<OutType>((OutType&)out.append(buffer,strle...
                       ^
./../MonaBase/include/Mona/String.h:255:10: note: in instantiation of function
      template specialization 'Mona::String::Append<Mona::String, char const
      (&)[3], unsigned int &, char const (&)[3], Mona::Media::Video::Frame &,
      char const (&)[2]>' requested here
                return Append<OutType>((OutType&)out.append(value, size ...
                       ^
./../MonaBase/include/Mona/String.h:240:10: note: in instantiation of function
      template specialization 'Mona::String::Append<Mona::String, const char,
      14, const unsigned int &, char const (&)[3], unsigned int &, char const
      (&)[3], Mona::Media::Video::Frame &, char const (&)[2]>' requested here
                return Append<OutType>((OutType&)out.append(value.data()...
                       ^
./../MonaBase/include/Mona/String.h:234:10: note: in instantiation of function
      template specialization 'Mona::String::Append<Mona::String, char const
      (&)[14], const unsigned int &, char const (&)[3], unsigned int &, char
      const (&)[3], Mona::Media::Video::Frame &, char const (&)[2]>' requested
      here
                return Append<OutType>(out, std::forward<Args>(args)...);
                       ^
./../MonaBase/include/Mona/Logs.h:82:11: note: in instantiation of function
      template specialization 'Mona::String::Assign<Mona::String, const
      std::__1::basic_string<char> &, char const (&)[14], const unsigned int &,
      char const (&)[3], unsigned int &, char const (&)[3],
      Mona::Media::Video::Frame &, char const (&)[2]>' requested here
                String::Assign(Message, std::forward<Args>(args)...);
                        ^
sources/Subscription.cpp:542:3: note: in instantiation of function template
      specialization 'Mona::Logs::Log<const std::__1::basic_string<char> &, char
      const (&)[14], const unsigned int &, char const (&)[3], unsigned int &,
      char const (&)[3], Mona::Media::Video::Frame &, char const (&)[2]>'
      requested here
                TRACE(pPublication->name(), " video time, ", tag.time, "...
                ^
./../MonaBase/include/Mona/Logs.h:193:20: note: expanded from macro 'TRACE'
#define TRACE(...)      LOG(Mona::LOG_TRACE, __VA_ARGS__)
                        ^
./../MonaBase/include/Mona/Logs.h:184:78: note: expanded from macro 'LOG'
  ......)  { if(Mona::Logs::GetLevel()>=(LEVEL)) { Mona::Logs::Log((LEVEL), _...
                                                               ^
./../MonaBase/include/Mona/String.h:333:18: note: candidate function [with
      OutType = Mona::String, Args = <char const (&)[2]>]
        static OutType& Append(OutType& out, int value, Args&&... args) {
                        ^
./../MonaBase/include/Mona/String.h:349:18: note: candidate function [with
      OutType = Mona::String, Args = <char const (&)[2]>]
        static OutType& Append(OutType& out, unsigned char value, Args&&...
                        ^
./../MonaBase/include/Mona/String.h:311:18: note: candidate function [with
      OutType = Mona::String, Args = <char const (&)[2]>]
        static OutType& Append(OutType& out, char value, Args&&... args) {
                        ^
./../MonaBase/include/Mona/String.h:317:18: note: candidate function [with
      OutType = Mona::String, Args = <char const (&)[2]>]
        static OutType& Append(OutType& out, signed char value, Args&&.....
                        ^
./../MonaBase/include/Mona/String.h:325:18: note: candidate function [with
      OutType = Mona::String, Args = <char const (&)[2]>]
        static OutType& Append(OutType& out, short value, Args&&... args) {
                        ^
./../MonaBase/include/Mona/String.h:341:18: note: candidate function [with
      OutType = Mona::String, Args = <char const (&)[2]>]
        static OutType& Append(OutType& out, long value, Args&&... args) {
                        ^
./../MonaBase/include/Mona/String.h:357:18: note: candidate function [with
      OutType = Mona::String, Args = <char const (&)[2]>]
        static OutType& Append(OutType& out, unsigned short value, Args&...
                        ^
./../MonaBase/include/Mona/String.h:365:18: note: candidate function [with
      OutType = Mona::String, Args = <char const (&)[2]>]
        static OutType& Append(OutType& out, unsigned int value, Args&&....
                        ^
./../MonaBase/include/Mona/String.h:373:18: note: candidate function [with
      OutType = Mona::String, Args = <char const (&)[2]>]
        static OutType& Append(OutType& out, unsigned long value, Args&&...
                        ^
./../MonaBase/include/Mona/String.h:381:18: note: candidate function [with
      OutType = Mona::String, Args = <char const (&)[2]>]
        static OutType& Append(OutType& out, long long value, Args&&... args) {
                        ^
./../MonaBase/include/Mona/String.h:389:18: note: candidate function [with
      OutType = Mona::String, Args = <char const (&)[2]>]
        static OutType& Append(OutType& out, unsigned long long value, A...
                        ^
./../MonaBase/include/Mona/String.h:397:18: note: candidate function [with
      OutType = Mona::String, Args = <char const (&)[2]>]
        static OutType& Append(OutType& out, float value, Args&&... args) {
                        ^
./../MonaBase/include/Mona/String.h:405:18: note: candidate function [with
      OutType = Mona::String, Args = <char const (&)[2]>]
        static OutType& Append(OutType& out, double value, Args&&... args) {
                        ^
./../MonaBase/include/Mona/String.h:413:18: note: candidate function [with
      OutType = Mona::String, Args = <char const (&)[2]>]
        static OutType& Append(OutType& out, bool value, Args&&... args) {
                        ^
1 error generated.
make[2]: *** [tmp/release/Subscription.o] Error 1
make[2]: `tmp/release/TCPSession.o' is up to date.
make[2]: `tmp/release/TCProtocol.o' is up to date.

**Comment by demiantres** [comment]
I am facing the same problem. Have you found a solution?

**Comment by akarupt** [comment]
no. please advise if you found one :)

**Comment by demiantres** [comment]
In sources/Subscription.cpp:542 you can comment out the "TRACE" line (don`t forget to add {} braces after the "if" statement).

**Comment by thomasjammet** [comment]
Thanks for your report! It is corrected in the last commit : 384d168faebee0ebf4d251be5241c77fa975d0c0
