### ISSUE TITLE
Implementing uWebSockets for best of breed server speed

### ISSUE THREAD

**Issue by gdeverlant** [MonaSolutions/MonaServer2#4]
Hi Thomas and Mathieu

I have stumbled upon this project and I thought that it could save you lots of time and efforts
trying to make MonaServer2 the fastest server out there....

I hope that is useful 

https://github.com/uWebSockets/uWebSockets

**Comment by thomasjammet** [comment]
Thanks, interesting project.
Do you have time to run the benchmark with MonaTiny?

**Comment by gdeverlant** [comment]
I just need to find a way to run MonaTiny on my 12 ARM64bits cluster
48 cores 22GB RAM can you help me with that ?

**Comment by thomasjammet** [comment]
Great job, I have finally take a look at the source code of uWebSockets and it seems a bit limited and mono-threaded, anyway when will have to improve the performances of the WebSocket protocol we could try the benchmark. Though we are already proud of our implementation, let's try it when you have time :)
