### ISSUE TITLE
Running MonaServer on RPI

### ISSUE THREAD

**Issue by quintendewilde** [MonaSolutions/MonaServer2#42]
I've installed all dependencies and installed monoserver when running ./MonaServer/MonaServer
I get file not found. I think I'm missing something here?

`collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:52: release] Error 1
make[1]: Leaving directory '/home/pi/MonaServer2/MonaTiny'
make: *** [Makefile:2: release] Error 2
pi@raspberrypi:~/MonaServer2 $ ./MonaServer/MonaServer
-bash: ./MonaServer/MonaServer: No such file or directory`

**Comment by MathieuPOUX** [comment]
Looks there is an error on MonaServer build (I see `[Makefile:2: release] Error 2`), could you give errors reported by the "make" done inside "/MonaServer" folder?

**Comment by quintendewilde** [comment]
Make inside the MonaServer folder results in : 

`creating executable MonaServer
/usr/bin/ld: cannot find -lMonaBase
/usr/bin/ld: cannot find -lMonaCore
collect2: error: ld returned 1 exit status
make: *** [Makefile:52: release] Error 1
`

**Comment by MathieuPOUX** [comment]
And in MonaBase folder it gives what?

**Comment by quintendewilde** [comment]
Mona base make gives no errors.

**Comment by MathieuPOUX** [comment]
I have just added -latomic link in the makefiles (https://github.com/MonaSolutions/MonaServer2/commit/4264513833d8cdac38746f256a035c721e1289c9)
Try after a pull if it works,
Thanks
