### ISSUE TITLE
VC 2019 compilation fixes

### ISSUE THREAD

**Issue by demiantres** [MonaSolutions/MonaServer2#45]
RTPReader.h, lines 56-59 fix:

		if (playloadType != _profile.playloadType) {
			ERROR(typeof<RTP_ProfileType>()," configured to receive ",_profile.playloadType," playload type and not ",playloadType)
			return 0;
		}

RTPWriter.h, lines 113-116:

 			if (isAudio)
				flush = _profile.writeAudio(tag, reader, writer, canWrite);
			else
				flush = _profile.writeVideo(tag, reader, writer, canWrite);

Here, I am not sure how to fix this. The problem is that "tag" is of the wrong type.

RTPWriter.h, line98: 

				_pBuffer.set(0);

**Comment by MathieuPOUX** [comment]
I have just now tried to fix your compilation issue with your description, I wait your feedback :-)
Thanks by this way!

**Comment by demiantres** [comment]
Thanks for the fix. It works.
