### ISSUE TITLE
Possible compilation problems with XCode due to "typeof" template

### ISSUE THREAD

**Issue by demiantres** [MonaSolutions/MonaServer2#46]
In the "Mona.h" header "typeof()" methods are defined (starting with line 300). When the project is compiled in XCode (version 12.4) then this leads to error messages.  Renaming the "typeof()" methods in the whole project fixes the problem:

    const` std::string& typeof(const std::type_info& info); // compilation errors
    const` std::string& typeofcustom(const std::type_info& info); // no compilation errors

**Comment by MathieuPOUX** [comment]
Thanks for reporting!

**Comment by MathieuPOUX** [comment]
It's fixed?
