### ISSUE TITLE
Thank you for help with SRT

### ISSUE THREAD

**Issue by Felk** [MonaSolutions/MonaServer2#48]
I know this is possible the worst place for this, but the [google groups thread](https://groups.google.com/g/monaserver/c/zcjl8GefdTg) won't let me respond to the thread, no matter what I try:

![image](https://user-images.githubusercontent.com/1996138/109214922-bd5ffa80-77b2-11eb-9780-3204942cd8b4.png)

I just wanted to let you know that I am very thankful for your quick response and help, and that your samples worked flawlessly. I was able to reduce latency from 1000ms with a (rtmp -> monaserver2 -> rtmp) setup to about 400ms with a (rtmp -> monaserver -> srt) setup. For reference the configuration I used is:

```
[stream=Publication]
OUT srt://@0.0.0.0:1234
```
with OBS streaming to `rtmp://127.0.0.1:1935/live` and vlc opening the network stream at `srt://127.0.0.1:1234`.

**Comment by thomasjammet** [comment]
Thanks for the report!
Sorry I have seen the google groups issue, for a strange reason the spam filter does not seem to allow me to accept the messages. Maybe it was the "imgur" links
