### ISSUE TITLE
main.lua Fail

### ISSUE THREAD

**Issue by jsnetcomm** [MonaSolutions/MonaServer2#49]
Hi, I'm trying to get MonaServer2 working but it gives me main.lua error.

/main.lua :: attempt to call method 'createUDPSocket' (a nil value) monaserver

Regards.

**Comment by MathieuPOUX** [comment]
Hi,

Use "newUDPSocket" rather.
Sorry MonaServer is neglected for the moment to consacre my time on an other adjoining project and its LUA part is instable. Use MonaTiny which is daily maintained, but doesn't support LUA extension...

**Comment by jsnetcomm** [comment]
Hello, thanks for answering.
now it throws me the following error
err = socket: bind ("0.0.0.0:1234") - start the server "attempt to index global 'socket' (a nil value)"
so surely the UDP port does not work for me.

**Comment by MathieuPOUX** [comment]
I have just now tried it, there was a address parsing issue but looks not relating with your pb:
```
socket = mona:newUDPSocket();
if socket:bind("0.0.0.0:1234") then
	print(socket:address())
end
```
You can catch possible address error as following (in passing in first argument a onError function to call on error):
```
socket = mona:newUDPSocket();
if socket:bind(error, "0.0.0.0:1234") then
	print(socket:address())
end
```

**Comment by jsnetcomm** [comment]
hello, it gives me the following error,
error == main.lua:10: attempt to get length of field 'clients' (a nil value)
does not read the ip's that enter
on line 10 of my main.lua I have =
INFO ("connected clients: ", #mona.clients);

**Comment by MathieuPOUX** [comment]
The LUA error says well the pb: mona object has no "clients" collection.
The pb is that you are applying Mona1 documentation to Mona2, whereas the API is quite different. I am aware that Mona2 documentation is missing on LUA, but unfortunatly my dedicated time doesn't allow me to fill that up today. Also keep in mind that LUA wrapper in Mona2 is always instable.
Maybe you can search by yourself in [LUAFiles in MonaServer code](https://github.com/MonaSolutions/MonaServer2/tree/master/MonaServer/sources): each file represents an object wrapped with its functions. For example [LUAMona.cpp defines "mona" API](https://github.com/MonaSolutions/MonaServer2/blob/master/MonaServer/sources/LUAMona.cpp). And if you get time to contribute to the project in writing a LUA API documentation it would be very much appreciate :-)
Sorry for that,
Thanks for your interest
