### ISSUE TITLE
Found another server project based on MonaServer

### ISSUE THREAD

**Issue by gdeverlant** [MonaSolutions/MonaServer2#5]
Hi guys while surfing I found the chinese using MonaServer and building something out of it...
I don't know if this can be useful for you guys because it seems that it might be interesting.

https://github.com/ossrs/srs

It seems that version 2.0 is improved a lot

https://github.com/ossrs/srs/tree/2.0release

There is chinese and english WIKI

2.0 https://github.com/ossrs/srs/wiki/v2_EN_Home

3.0 https://github.com/ossrs/srs/wiki/v3_EN_Home

**Comment by thomasjammet** [comment]
Hi, thanks, how do you know that they use MonaServer?

**Comment by gdeverlant** [comment]
Because the chinese never create something they steal and copy everything ...

No I'm joking ... you can contact the developers and ask them they will confirm you.

**Comment by thomasjammet** [comment]
Ok, thank you for the information, I don't see the Mona sources into their repository but I guess it is used in some custom version.
