### ISSUE TITLE
Cannot access RTMFP or SRT over public IP/from internet

### ISSUE THREAD

**Issue by instinctualjealousy** [MonaSolutions/MonaServer2#50]
Let me preface this- I doubt this is the fault of MonaServer, but it's more of a just-in-case or perhaps if someone has the answer, someone can find out why. Either that, or my router is being a dumbdumb. I really don't think it's ISP stuff. Feel free to remove or close- this isn't a support forum, I know.

I recently switched to MonaServer2. I had been using nginx-rtmp to pass RTMP livestreams to my girlfriend (and receive from her) for over a couple years. It worked and MonaServer works for this as well- I switched since Mona supports SRT now.

I know how to do port forwarding. RTMP and HTTP (1935 and 80 TCP) have been forwarding correctly and work great. 8000 for Icecast as well. This is all TCP, however.

RTMFP, which uses 1935 also, will not work from outside my LAN- and yes, I set my forward rule to "both" as RTMFP is a UDP protocol. 9710 UDP was also opened for SRT. I've rebooted my router.

The ports *are* listening correctly, I can access the SRT and RTMFP streams just fine on the same LAN, but when accessing from the internet, it hits a wall as if the ports were closed.

MonaServer2 is running on a Debian 10 x64 computer, cleanly compiled from latest master as of yesterday, same with SRT, it compiled without errors and has been working great.

I do run through a AirStation wirelessly bridging me- on same subnet, no firewalling going on there, it's a true wireless bridge. The TP-Link downstairs is a 2019 Archer C5 (AC1200) that is connected to a DSL modem in bridge mode so I don't double NAT. It's worked great so far. I'd hate to have to try a different router. I know I've successfully forwarded UDP ports in the past!

Thanks for the trouble if anyone can think of anything to troubleshoot this, and if there's a better place for me to post crap like this, that's fine too.

**Comment by instinctualjealousy** [comment]
I'm starting to think my router refuses to forward UDP packets. This might be a lost cause. Feel free to remove or close (=

**Comment by thomasjammet** [comment]
Hi!

There is no problem for posting this issue ;)
Did you resolve it? I was thinking of a problem of iptables rules but you said that there is no firewall, right? If not already done maybe you can try to disable iptables (`iptables -F`) on **both server and client side**.

Also to be sure that it does not come from the protocol usage the best is to test with netcat. For example to start a UDP server on port 4567 :
`nc -u -l 4567`
And to send a message to this server, run the following command, then type a message + ENTER :
`nc -u <host> 4567`

**Comment by instinctualjealousy** [comment]
Thanks for your curiosity. I even switched back to the old router I used when I was port forwarding 2310 for Re-Volt multiplayer and it was working. My girlfriend said when I forwarded it, she would get a "connection rejected by host", and when I did not, she would get a connection timeout (same result on both routers). I also noticed traceroute on Linux would do two hops on my IP for a forwarded TCP port, one hop for an unforwarded TCP port, but UDP would always be one hop.

I haven't done a netcat yet though. I honestly decided to give up- nothing's different on my end now than back when I was successfully forwarding 2310 UDP, so I can't blame the router. I'm thinking it's ISP related. Also, I disabled my Windows Firewall just in case for testing purposes (but I do have an exception for Re-Volt), and my Linux iptables is blank as far as I know (will double check though)

It still is worth noting how flawless TCP forwarding is still for me. I don't think MonaServer's the problem, I had the same problem when I was messing with srt-live-server, but SRT is a more complex protocol to figure out. I could chalk up some things to inexperience or user error. RTMFP on the other hand was the real hint- it's a very similar protocol to RTMP, and even with the UDP 1935 forwarded, it would fail to work over the net (using your videoplayer.swf on monaserver.ovh to test). Everything worked fine when accessed on the LAN, too.

Anyway, thank you for the information and if anything does change I'll be sure to bring it up. And thanks for the hard work you've put into this. It's the best fully-free solution I've found out there, which is great for people like me who are just doing a small hobbyist thing rather than a commercial enterprise. (=

**Comment by thomasjammet** [comment]
Thanks for your explanation! It's strange and if you have time to debug this it would be great. There is no reason for UDP to not work unless there is a specific firewall configuration. Definitely testing using netcat could help.

About the rendezvous mode it's an interesting idea, for now it is not implemented in MonaServer but we will think about it. Of course this would need to setup static SRT configuration in the .ini file with a custom server address and a custom client adress on the other endpoint.

**Comment by b3ck** [comment]
How would I setup a publication that has SRT 'IN' using HEVC and goes 'OUT' via HTTPS to a test.mp4 ?

**Comment by thomasjammet** [comment]
Please don't post twice, I have answered to your question here : 
https://github.com/MonaSolutions/MonaServer2/issues/51#issuecomment-822224763
