### ISSUE TITLE
SRT with MonServer2

### ISSUE THREAD

**Issue by b3ck** [MonaSolutions/MonaServer2#51]
I followed instructions to add SRT to MonaServer2, but no dice.

I am able to build both debug and release versions of 32 bit and 64 bit MonaServer2.

No matter how I add the header files and lib files I am still unable to see any type of SRT server in the console.
- I have even disabled all other servers and made `[SRT=true]`, still.. nothing.

Please advise.

```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 Build 19042
VS Version:                16.9.4
```

`\\End of line`

**Comment by MathieuPOUX** [comment]
Have you built the SRT libraries, and put it in folder as following?
```
MonaServer/External/lib/pthread_lib.lib
MonaServer/External/lib/pthread_libd.lib
MonaServer/External/lib/srt_static.lib
MonaServer/External/lib/srt_staticd.lib
MonaServer/External/lib64/pthread_lib.lib
MonaServer/External/lib64/pthread_libd.lib
MonaServer/External/lib64/srt_static.lib
MonaServer/External/lib64/srt_staticd.lib
```

**Comment by b3ck** [comment]
Yes I have.

**Comment by MathieuPOUX** [comment]
I figure that the includes files are also their right location (External/include/srt), strange, I have just tested now to be sure with a fresh clone, it works one time include and libs installed. You build with Visual Community 2019?
Check when you build that this inclusion link well to srt/srt.h right file:
https://github.com/MonaSolutions/MonaServer2/blob/master/MonaBase/include/Mona/SRT.h#L22
And define well constant STR_API.

**Comment by b3ck** [comment]
Yes I am using Visual Studio 2019, SRT was built with it as well, SRT works just fine from my build, I don't understand why it's not working. :Ugh:

**Comment by MathieuPOUX** [comment]
Inside Visual Studio 2019 if you make F12 on the inclusion [line 22 of SRT.h](https://github.com/MonaSolutions/MonaServer2/blob/master/MonaBase/include/Mona/SRT.h#L22), you get the following file which defines SRT_API?
![image](https://user-images.githubusercontent.com/5681621/115120861-fc8b1a80-9faf-11eb-83ae-d170d118ab80.png)

**Comment by b3ck** [comment]
okay this is a little misleading, the instructions didn't say anything about having anything in MonaBase, just in Mona Server.. so what files need to be where? because when I press F12 on line 22 in SRT.h in MonaBase it says `no definition found for 'srt'`, does this mean I need to put all of those files in the `MonaBase/include/Mona/` directory?

**Comment by b3ck** [comment]
if I open up the full Mona.sln in Visual Studio 19 and go into the SRT.h under Net for MonaBase and press F12 on line 22 it just opens up another srt.h which displays this:

![image](https://user-images.githubusercontent.com/1740542/115135512-a97c8c00-9fde-11eb-80ba-135547a8a0c1.png)

**Comment by b3ck** [comment]
I found out SRT is built into MonyTiny, so I'll worry about building SRT myself later;

So how does SRT with MonaTiny work? how can I define a `streamid` and then view the feed in something like VLC or OBS?

**Comment by MathieuPOUX** [comment]
If MonaTiny build and find SRT, no pb for MonaServer, build it inside Visual Studio 2019 (not visual code) and it will work same (If you see your first pb reported by F12 you was pointed not the good SRT file, like if SRt header files was not present, but now that MonaTiny has copied it it would be fine).
To publish:
https://docs.google.com/document/d/1cFhsGHtlALM3AajktEhVzXzfn5rfa5_e7djUYWawsrM/edit#heading=h.itzgm67bh31s
To play:
https://docs.google.com/document/d/1cFhsGHtlALM3AajktEhVzXzfn5rfa5_e7djUYWawsrM/edit#heading=h.qh1hfkhz7ack

**Comment by b3ck** [comment]
I've been all over these documents and have tried everything that I can think of, like I said I am able to have a stable SRT connect from Larix to the SRT server in MonaTiny, but how do I play it in OBS? Everything I have tried doesn't work.

I need real world examples, not just links to documentation.


Thanks and Kind Regards,
-b3ck

**Comment by b3ck** [comment]
So I was able to get sound, but no video using HEVC, when I switch it over to h.264 I get video and sound.

How would I setup a publication that has SRT in using HEVC and goes OUT via HTTPS to a test.mp4 ?

**Comment by b3ck** [comment]
I keep getting these errors in the console:

```
MediaWriter.cpp[138] NALNetWriter<HEVC> doesn't support multitrack
HEVC.cpp[143] HEVC configuration malformed
MP4Writer.cpp[264] No avcC configuration
```

**Comment by thomasjammet** [comment]
Hi

I think there is a known issue with avcC parsing that we should fix, we will dig into it ASAP but we have not enough time for this right now.

Though you can use MPEGTS output through HTTPS if it's fine for you, I have tested it this morning and it works fine.
The following configuration is sufficient :
```
[test123=Publication]
IN srt://0.0.0.0:1234
```

And in vlc you can play the stream using the link https://127.0.0.1/test123.ts

**Comment by b3ck** [comment]
So with this example in larix I stream to IP:1234, streamid: test123, then it will automatically be able to be seen from https://127.0.0.1/test123.ts ?

**Comment by thomasjammet** [comment]
That's fine, it should work now. Maybe try with HTTP (without S)

Otherwise there is a problem with the input, do you have a log like the following when you start pushing to Mona?
![immagine](https://user-images.githubusercontent.com/3465354/115196602-64e11580-a0f0-11eb-8346-8c132ac7147e.png)

**Comment by b3ck** [comment]
Got it, yeah works with h.264, but not h.265 =(

**Comment by b3ck** [comment]
this is what it looks like, don't worry it's a mobile IP:

![image](https://user-images.githubusercontent.com/1740542/115197458-9fc65780-a0b6-11eb-8ccc-65d6329a6c14.png)

**Comment by b3ck** [comment]
Also is there a way to show incoming bitrates for active Publications in json format?

This is all I see from the informations:
![image](https://user-images.githubusercontent.com/1740542/115200399-cb970c80-a0b9-11eb-8566-f6db46e90195.png)

**Comment by b3ck** [comment]
Seems like there was an issue with my SRT encoder, just updated the firmware and now HEVC (h.265) works with MonaTiny SRT, so now that works, how can I see the bitrate and RTT of an SRT stream?

**Comment by b3ck** [comment]
Seems like there was an issue with my SRT encoder, just updated the firmware and now HEVC (h.265) works with MonaTiny SRT.
