### ISSUE TITLE
SRT Publication with Passphrase/Encryption

### ISSUE THREAD

**Issue by ja-cop** [MonaSolutions/MonaServer2#55]
Hello,

Thank you for this immensely useful software.

I've successfully been using MonaServer and SRT for a while, but without encryption. In my setup, OBS publishes a stream to MonaServer, and VLC or mpv/ffmpeg receives an SRT publication of that stream to play it back.

However, now I want to set up encryption and I'm having trouble.

My configuration looks like this:
```ini
[SRT=true]
; socket bind
port=9710
host=127.0.0.1
publicPort=9710
publicHost=127.0.0.1
; socket parameters, if not set use [net] parameters (see above in CATEGORIZED)
bufferSize=65536
recvBufferSize=65536
sendBufferSize=65536
; SRTO_TLPKTDROP, see https://github.com/Haivision/srt/blob/master/docs/API.md#options
pktdrop=true
; SRTO_PBKEYLEN, see https://github.com/Haivision/srt/blob/master/docs/API.md#options
encryption=0
; SRTO_PASSPHRASE, see https://github.com/Haivision/srt/blob/master/docs/API.md#options
passphrase="publish_passphrase"
; SRTO_RCVLATENCY, see https://github.com/Haivision/srt/blob/master/docs/API.md#options
latency=120
; SRTO_PEERLATENCY, see https://github.com/Haivision/srt/blob/master/docs/API.md#options
peerlatency=0
; SRTO_MSS, see https://github.com/Haivision/srt/blob/master/docs/API.md#options
mss=1500
; SRTO_OHEADBW, see https://github.com/Haivision/srt/blob/master/docs/API.md#options
overheadbw=25
; SRTO_MAXBW, see https://github.com/Haivision/srt/blob/master/docs/API.md#options
maxbw=-1

[RTMFP=false]
[RTMP=false]
[HTTPS=false]
[WS=false]
[WSS=false]

[live=publication]
passphrase="publication_passphrase"
OUT srt://0.0.0.0:5678
```

Encryption works for receiving the stream from OBS on port 9710 by configuring OBS to stream to `srt://127.0.0.1:9710/?streamid=#!::r=live,m=publish&passphrase=publish_passphrase`. Without including the `passphrase` option in the URL, the connection is rejected as intended.

The publication is created, but it doesn't seem to use encryption. I can successfully connect and play the stream with mpv like `mpv srt://localhost:5678`. No passphrase option is required.

**How can I enable and enforce encryption on SRT publications?**

edit:

I also tried the following:

```ini
[live=publication]
OUT srt://0.0.0.0:5678?passphrase=publication_passphrase
```

This doesn't work either; mpv can still play it back without providing a passphrase.

**Comment by thomasjammet** [comment]
Hi!

Thank you for your report, the configuration samples were not complete, you were near to the solution, this is how to pass your parameters for the protocol :
```
[live=publication]
OUT srt://0.0.0.0:5678 ?passphrase=publication_passphrase
```

As you can see only the space was missing.
And here is the updated sample in MonaServer.ini : 
https://github.com/MonaSolutions/MonaServer2/blob/master/MonaServer/MonaServer.ini#L286

**Comment by ja-cop** [comment]
Thanks a lot, that works! For completeness, here's how to play back such a stream with mpv:

```
mpv 'srt://localhost:5678?passphrase=publication_passphrase'
```

**Comment by ja-cop** [comment]
@abdallagheryani69 hello,

I've since switched to using mediamtx with RTMP for this purpose, but when I was using MonaServer my publish URL was something like this:

```text
srt://youraddress:9710/?streamid=#!::r=ja_cop,m=publish&passphrase=<my passphrase>
```
