### ISSUE TITLE
Found a great clustering solution for MonaServer

### ISSUE THREAD

**Issue by gdeverlant** [MonaSolutions/MonaServer2#6]
Hi Mathieu and Thomas I have found a great project that we can implement inside of Mona for the clustering part.

ArangoDB and RethinkDB are using some kind of a HTTP Api bridge to make the nodes connect to each others. I thought that right now Mona's scaling setting are pretty static and not dynamic in a docker swarm context.

I would like you to check out this Go project and tell me if we can make Mona interact with it via HTTP so that we can let Mona apply dynamic/host clustering on the fly.

https://github.com/arangodb-helper/ArangoDBStarter

Thanx

**Comment by thomasjammet** [comment]
Hi,

Yes you can send HTTP requests from Mona using the [TCP Client API](http://www.monaserver.ovh/serversocket.html#tcp-client), send me a mail if you need more help, we have already used HTTP for other projects.
