### ISSUE TITLE
MonaServer gitter community

### ISSUE THREAD

**Issue by gdeverlant** [MonaSolutions/MonaServer2#7]
I thought we need a place for MonaServer where we can exchange in realtime.

https://gitter.im/MonaServer

Let's make this beautiful piece of code become a standard!

**Comment by MathieuPOUX** [comment]
Hi,

Thanks for your interest,
Mona will grow up a lot in the 1-2 following years, and sorry if it takes time, the project is very ambitious.
I have added your link on [main page](https://github.com/MonaSolutions/MonaServer2/commit/06f4cf07c61f001cefbabdef993c88888fe7be72).

Best,
Mathieu
